---
- name: stop and disable unwanted services
  systemd: name={{ item }} state=stopped enabled=no
  with_items:
    - rpcbind
    - rpcbind.socket
    - postfix


- name: start and enable wanted services
  systemd: name={{ item }} state=started enabled=yes
  with_items:
    - firewalld
