---
- name: install Zabbix repo
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm
    state: present


- name: install packages
  yum:
    name: zabbix-agent
    state: present


- name: copy config zabbix agent
  copy:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/
  notify: restart zabbix-agent


- name: start and enable service
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes


- name: configure firewalld
  firewalld:
    service: zabbix-agent
    state: enabled
    permanent: yes
    immediate: yes
