---
- name: install Zabbix repo
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm
    state: present


- name: install packages
  yum:
    name:
      - zabbix-server-pgsql
      - zabbix-web-pgsql
      - policycoreutils
    state: present


- name: disable service
  systemd:
    name: zabbix-server
    enabled: no


- include_tasks: nginx.yml
- include_tasks: php-fpm.yml


- name: fix permission
  file:
    path: /etc/zabbix/web/
    group: nginx


- name: copy config for zabbix web
  copy:
    src: zabbix/zabbix.conf.php
    dest: /etc/zabbix/web/


- name: copy config for zabbix server
  copy:
    src: zabbix/zabbix_server.conf
    dest: /etc/zabbix


- name: copy semodule in /tmp
  copy: src=zabbix/{{ item }} dest='/tmp/'
  with_items:
    - otus_zabbix.pp
    - otus_zabbix_http.pp
    - otus_zabbix_postgresql.pp


- name: install semodule
  command: 'semodule -i /tmp/{{ item }}'
  with_items:
    - otus_zabbix.pp
    - otus_zabbix_http.pp
    - otus_zabbix_postgresql.pp


- name: configure firewalld
  firewalld:
    service: zabbix-server
    state: enabled
    permanent: yes
    immediate: yes
